yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from . import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied_view'
handler500 = 'core.views.custom_500'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

STR_LENGTH = 15

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Название группы',
        max_length=200,
        help_text='Укажите название группы')
    slug = models.SlugField(
        verbose_name='Адрес группы',
        max_length=50,
        unique=True,
        blank=True,
        help_text=(
            'Укажите уникальный адрес для страницы группы. '
            'Используйте только латиницу, цифры, дефисы и знаки подчёркивания'
        ))
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Добавьте описание группы')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
        help_text='Дата публикации (ставится автоматически)'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор поста',
        related_name='posts',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Сообщество',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        help_text='Укажите, к какой группе относится пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:STR_LENGTH]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
        related_name='comments',
        help_text='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария',
        related_name='comments',
        help_text='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата комментария',
        auto_now_add=True,
        help_text='Дата комментария (ставится автоматически)'
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text[:STR_LENGTH]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписавшийся',
        help_text='Пользователь, который подписывается на автора'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        ordering = ['-user']
        unique_together = ('user', 'author')

    def __str__(self):
        return self.user.username

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow

COUNT_OF_POSTS_ON_PAGE = 10


def get_paginator(request, posts):
    paginator = Paginator(posts, COUNT_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.all()
    page_obj = get_paginator(request, posts)
    context = {'page_obj': page_obj, }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    group_obj = group.posts.all()
    page_obj = get_paginator(request, group_obj)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_of_author = Post.objects.filter(author=author)
    page_obj = get_paginator(request, posts_of_author)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user)
        return render(request, 'posts/create_post.html', {'form': form})
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author == request.user:
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post.id)
        context = {
            'is_edit': True,
            'form': form,
            'post': post,
        }
        return render(request, 'posts/create_post.html', context)
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        post = get_object_or_404(Post, pk=post_id)
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    selected_posts = Post.objects.filter(author__following__user=request.user)
    page_obj = get_paginator(request, selected_posts)
    context = {'page_obj': page_obj, }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %} 
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}        
          </div>
          <div class="card-body">    
            {% include 'includes/validation.html' %}    
            <form method="post" 
              enctype="multipart/form-data"
              {% if is_edit %} 
                action={% url 'posts:post_edit' post.id %}
              {% else %} 
                action={% url 'posts:post_create' %}
              {% endif %}>
              {% csrf_token %}
              {% include 'includes/form_mapping.html' %} 
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Посты авторов, на которых я подписан{% endblock %}
{% block content %}
<div class="container py-5">
<h1>Посты авторов, на которых я подписан</h1>
{% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
            <article>
            <ul>
                <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">
                    все посты пользователя
                </a>
                {% include 'posts/includes/postcard.html' %}
            </article>
            {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% include 'posts/includes/load_thumbnail.html' %}
        <p>{{ post.text }}</p>
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    {% load cache %}
      {% cache 1 sidebar index_page %}
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">
                  все посты пользователя
                </a>
              </li>
              {% include 'posts/includes/postcard.html' %}
            </ul>
          </article>      {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      {% endcache %} 
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post.text|truncatechars:30}}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}   
            <li class="list-group-item">
              Группа: {{ post.group }} 
              <a href="{% url 'posts:posts' post.group.slug %}">
                <br>все записи группы
              </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  
            <span style="color:red; font-size:150%" > 
              {{ post.author.posts.count }}  
            </span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' user %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% include 'posts/includes/load_thumbnail.html' %}
        <p>{{ post.text }}</p>
        {% if post.author == user%}
          <a class="btn btn-primary" 
            href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
        {% endif %}
        {% if request.user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action={% url 'posts:add_comment' post.id %}>
                {% csrf_token %}
                {% include 'includes/form_mapping.html' %} 
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text }}
              </p>
            </div>
          </div>
        {% endfor %} 
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}{{author.get_full_name}} профайл пользователя{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="mb-5">       
          <h1>Все посты пользователя {{author.get_full_name}} </h1>
          <h3>Всего постов: {{author.posts.count}} </h3>   
          {% if request.user.is_authenticated and request.user != author %}
            {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
            {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
                Подписаться
              </a>
            {% endif %}
          {% endif %}
          {% for post in page_obj %}
            <article>    
              <ul>
              {% include 'posts/includes/postcard.html' %}
            </article> {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
        </div>
      </div>
{% endblock %}